function FindProxyForURL(url, host) {
    // Convert the hostname to lowercase for accurate matching
    host = host.toLowerCase();

    // =========================================================================
    // 1. ALLOWLIST DOMAINS (Direct Connection / Unblocked)
    // =========================================================================
    var allowList = [
        "www.google-analytics.com",
        "beacons3.gvt2.com",
        "beacons.gcp.gvt2.com",
        "beacons5.gvt3.com",
        "aepxlg.adobe.com",
        "ipm.avcdn.net",
        "qwps.cn",
        "wps.cn",
        "ncc.avast.com",
        "scribd.com",
        "youtube.com",
        "youtube.in",
        "google.com"
    ];

    for (var i = 0; i < allowList.length; i++) {
        if (dnsDomainIs(host, allowList[i]) || localHostOrDomainIs(host, allowList[i])) {
            return "DIRECT";
        }
    }

    // =========================================================================
    // 2. DENYLIST DOMAINS (Routed through Proxy / Blocked)
    // =========================================================================
    var denyList = [
        "1.anime4up.tv", "1.aniwave.ch", "1.kickassanime.mx", "1.otakustv.com",
        "100girlfriends.com", "123anime.biz", "123anime.cc", "123anime.club",
        "123anime.co", "123anime.com", "123anime.fun", "123anime.info",
        "123anime.la", "123anime.me", "123anime.mobi", "123anime.net",
        "123anime.org", "123anime.pw", "123anime.watch", "123anime.xyz",
        "123anime123.com", "123animehd.com", "123animehub.cc", "123animehub.com",
        "123animehub.net", "123animes.biz", "123animes.cc", "123animes.co",
        "123animes.com", "123animes.ga", "123animes.info", "123animes.me",
        "123animes.mobi", "123animes.net", "123animes.online", "123animes.org",
        "123animes.ws", "123kissanime.com", "13dl.me", "141jav.com",
        "141ppv.com", "18comic.org", "18comic.vip", "1999.co.jp",
        "1anime.co", "1anime.one", "1anime.online", "1anime.to",
        "1fe84bc728af-stremio-anime-catalogs.baby-beamup.club", "1lib.sk", "1manga.co", "1piecemanga.com",
        "1st-kissmanga.net", "1st-kissmanga.online", "1stkissanime.com", "1stkissmanga.io",
        "1stkissnovel.org", "1xanimes.in", "1xanime.com", "1zumii.github.io",
        "21-draw.com", "23qb.net", "2dcomplex.com", "2disbetterthan3d.wordpress.com",
        "2gantzmanga.iespana.es", "2kissanime.com", "2krota.ru", "3.animeflv.net",
        "3.animeonline.ninja", "3.nhk.or.jp", "3asq.org", "3d.nicovideo.jp",
        "43d.github.io", "4anime.best", "4anime.biz", "4anime.cc",
        "4anime.cf", "4anime.ch", "4anime.city", "4anime.click",
        "4anime.club", "4anime.co", "4anime.com", "4anime.cyou",
        "4anime.cz", "4anime.de", "4anime.dev", "4anime.email",
        "4anime.eu", "4anime.fun", "4anime.ga", "4anime.gg",
        "4anime.gq", "4anime.in", "4anime.info", "4anime.io",
        "4anime.life", "4anime.link", "4anime.live", "4anime.me",
        "4anime.ml", "4anime.moe", "4anime.monster", "4anime.net",
        "4anime.nl", "4anime.one", "4anime.online", "4anime.org",
        "4anime.pro", "4anime.site", "4anime.so", "4anime.stream",
        "4anime.to", "4anime.top", "4anime.tv", "4anime.uno",
        "4anime.video", "4anime.vip", "4anime.watch", "4anime.work",
        "4anime.ws", "4anime.xyz", "4anime2.com", "4animepro.com",
        "4animes.biz", "4animes.com", "4animes.de", "4animes.org",
        "4animes.to", "4animes.tv", "4animeto.com", "4animeto.xyz",
        "4animetv.ml", "4animetv.net", "4animetv.online", "4animetvhd.com",
        "4gamer.net", "4kissanime.com", "55comic.com", "600ml.com",
        "69xinshu.com", "7a625ac658ec-animeo.baby-beamup.club", "82novel.com", "9anime-to.net",
        "9anime-tv.com", "9anime.bid", "9anime.bond", "9anime.by",
        "9anime.city", "9anime.co.ba", "9anime.co.bz", "9anime.com.pl",
        "9anime.com.tc", "9anime.gg", "9anime.gs", "9anime.id",
        "9anime.is", "9anime.me", "9anime.org", "9anime.org.lv",
        "9anime.org.tw", "9anime.ph", "9anime.pl", "9anime.pro.in",
        "9anime.se", "9anime.social", "9anime.to", "9anime.vip",
        "9anime2.com", "9animehq.to", "9animelab.com", "9animes.io",
        "9animes.my", "9animes.org", "9animes.ph", "9animes.ru",
        "9animeto.io", "9animetv.to", "9hentai.com", "9hentai.so",
        "9hentai.to", "9kissanime.com", "9tsu.cc", "a-will-eternal.fandom.com",
        "a-zmanga.net", "a06.kotbc2.com", "a24.ohli24.com", "a4.asurahosting.com",
        "aasurrscans.com", "abakascans.com", "about.lezhin.com", "acg.rip",
        "acgnx.se", "ack72.github.io", "adkami.com", "adultcomic.dbsearch.net",
        "adultcomic.uk", "adultcomixxx.com", "adultcomixxx.to", "aegir.mantton.com",
        "aesthetics.fandom.com", "afroditscans.com", "agedm.org", "agit367.com",
        "agith.cerestia.net", "agscomics.com", "aidn.jp", "aidoku.app",
        "aidoru-online.me", "aifu2x.udp.jp", "aifuxl.com", "ajinmanga.online",
        "akari-psi.vercel.app", "akata.fr", "akatzuki.fullboards.com", "akb48.co.jp",
        "akiharu.foroes.net", "akiharufansub.wordpress.com", "akihaydeto.net", "akilli.tv",
        "akross.ru", "akuma-no-fansub.com", "akuma.moe", "alafista.com",
        "alandal.com", "alexmaven.com", "algunanime.blogspot.com", "aliceoseman.com",
        "alist.thdisc.tk", "all-wish.me", "allanime.to", "allanimemags.com",
        "allhaven.cc", "allkpop.com", "allmanga.to", "allmangasreader.com",
        "allnovel.org", "allnovelbook.com", "allporncomic.io", "allporncomic.to",
        "allstarcomics.com.au", "allthetropes.org", "alpha-manga.com", "alurasworld.cerestia.net",
        "alurasworld.metropoliglobal.com", "amalgam-fansubs.moe", "amanteanime.blogspot.com", "amarullz.com",
        "amatsukaze.rl404.com", "amiami.com", "amiaopensource.github.io", "aminoapps.com",
        "amvhell.com", "amvnews.ru", "amvstr.me", "an0ncer.github.io",
        "an1me.io", "anacreondjt.gitlab.io", "anderer.moe", "androidvisualnovels.blogspot.com",
        "androidvisualnovels2.wordpress.com", "angelfairies.awardspace.com", "angelfire.com", "angelicanimanga.foroslatin.com",
        "ani-kei.fatal.ru", "ani.freemovies.homes", "ani.me", "ani4u.org",
        "aniabout.com", "anianimals.moe", "aniblogtracker.com", "anibrain.ai",
        "anibunker.com", "anica.jp", "anichart.net", "anicheck.moe",
        "aniconnections.com", "anicrush.to", "aniculmedia.com", "anidb.net",
        "anidex.info", "anidl.org", "anidub.pro", "anifilm.net",
        "aniforest.com", "anifox.club", "anify.tv", "anigliscans.xyz",
        "aniguessr.com", "anihonetwallpaper.com", "anikai.to", "anikani.com",
        "anikore.jp", "anikoto.to", "anikoto.tv", "anilibria.top",
        "anilife.live", "aniland.org", "anilinkz.com", "anilinkz.to",
        "anilist-adaptations.timschneeberger.me", "anilist.co", "anim-area11.net", "animafan.biz",
        "animalog.online", "animanga.fandom.com", "animangafanaticos.net", "animania.app",
        "animate-onlineshop.jp", "animation.filmarchives.jp", "animationdigitalnetwork.fr", "animationobsessive.substack.com",
        "animax-la.com", "anime-100.com", "anime-archive.com", "anime-bingo.aikats.us",
        "anime-edge.com", "anime-expo.org", "anime-fansubs.de", "anime-japan.jp",
        "anime-kisses.com", "anime-loads.org", "anime-odcinki.pl", "anime-overdose.com",
        "anime-pictures.net", "anime-planet.com", "anime-planet.superforo.net", "anime-reactor.net",
        "anime-sama.fr", "anime-sama.me", "anime-sharing.com", "anime-skip.com",
        "anime-stats.net", "anime-story.com", "anime-subtitle-player.vercel.app", "anime-ticonofansub.blogspot.com",
        "anime-ticonofansub.foroactivo.net", "anime-tourism.jp", "anime-town.com", "anime-world.in",
        "anime.adgstudios.co.za", "anime.ameo.dev", "anime.com", "anime.dbsearch.net",
        "anime.eiga.com", "anime.en.malavida.com", "anime.es", "anime.livedoor.com",
        "anime.nexus", "anime.plus", "anime.stackexchange.com", "anime.uhuyy.dev",
        "anime.uniquestream.net", "anime00.com", "anime1.com", "anime2watch.tv",
        "anime47.cam", "anime4i.com", "anime4you.one", "anime8.ru",
        "anime8dao.com", "animea.net", "animeacademy.in", "animeacademy.io",
        "animeafterglow.wordpress.com", "animeast.com", "animeazing.nl", "animebahu.top",
        "animebalkan.gg", "animebalkan.org", "animebathscenewiki.com", "animebeeto.blogspot.com",
        "animebits.moe", "animeblogger.net", "animeblogz.com", "animebook.github.io",
        "animeboston.com", "animebox.org", "animeboy.org", "animebreaker.com",
        "animebuff.ru", "animebytes.tv", "animecards.site", "animecastle.com",
        "animecenterscan.com", "animecentral.ge", "animechecker.sourceforge.net", "animeclips.online",
        "animecollective.com", "animecorner.me", "animecountdown.com", "animecrush.to",
        "animedaily.net", "animedao.ac", "animedao.com.ru", "animedao.to",
        "animedb.jp", "animediclous.tk", "animedub.pro", "animeday.tv",
        "animefenix.com", "animefenix.tv", "animefever.cc", "animefillerguide.com",
        "animefillerlist.com", "animefire.net", "animeflix.domains", "animeflix.gg",
        "animeflix.io", "animeflix.li", "animeflix.live", "animeflix.ltd",
        "animeflix.website", "animeflv.net", "animeforums.net", "animefox.fun",
        "animefox.in", "animefox.mobi", "animefoxbrasil.blogspot.com", "animefreak.to",
        "animefreak.video", "animefrenzy.net", "animefrenzy.org", "animegg.org",
        "animeglobal.net", "animego.org", "animeguess.moe", "animehade.net",
        "animehay.in", "animeheaven.es", "animeheaven.eu", "animeheaven.me",
        "animeheaven.mobi", "animeheaven.org", "animeheaven.pages.dev", "animeheaven.pl",
        "animeheaven.pro", "animeheaven.to", "animeheaven.top", "animehell.servermh.net",
        "animehol.com", "animehub.ac", "animehub.to", "animehud.online",
        "animeid.com", "animeid.es", "animeid.tv", "animeidhentai.com",
        "animeil-tv.com", "animeindo.co", "animeisme.net", "animejoy.ru",
        "animek.app", "animek.fun", "animek.inc", "animekai.bz",
        "animekai.com", "animekai.to", "animekaizoku.xyz", "animekarmalist.com",
        "animekarmawatch.com", "animekhor.org", "animekhor.xyz", "animekisa.net",
        "animekisa.tv", "animekissa.tv", "animeko.co", "animelab.ca",
        "animelab.club", "animelab.co", "animelab.com", "animelab.de",
        "animelab.eu", "animelab.ga", "animelab.icu", "animelab.in",
        "animelab.me", "animelab.net", "animelab.online", "animelab.org",
        "animelab.ro", "animelab.rocks", "animelab.store", "animelab.top",
        "animeland.fr", "animeland.tv", "animelayer.ru", "animelegends.org",
        "animelek.me", "animelon.com", "animelosangeles.org", "animelords.net",
        "animemangascans.tumblr.com", "animemap.com", "animemusicquiz.com", "animemusicvideos.org",
        "animemusicvids.net", "animemotivation.com", "animenana.com", "animenano.com",
        "animenerdz.blogspot.com", "animenewsnetwork.com", "animenexus.cc", "animenexus.net",
        "animenexus.tv", "animenfo.com", "animenosub.com", "animenosub.to",
        "animenova.jp", "animenow.to", "animension--v8.pages.dev", "animentodadescarga.blogspot.com",
        "animeobt.xyz", "animeology.in", "animeomega.com", "animeonline.ninja",
        "animeonlinetv.org", "animeonsen.xyz", "animeopeningsongs.com", "animeout.xyz",
        "animeowl-w1.pages.dev", "animeowl.live", "animeowl.net", "animepahe.ac",
        "animepahe.com", "animepahe.org", "animepahe.ru", "animepalm.com", "animeparadise.moe",
        "animeparadise.net", "animeportal.gr", "animeprofile.com.br", "animeradio.de",
        "animeraja.in", "animeram.online", "animerco.com", "animerdle.com",
        "animerealms.org", "animerebirth.com", "animeremux.xyz", "animerevival.xyz",
        "animerss.com", "animerulz.in", "animerush.tv", "animes-streaming.net",
        "animes.vision", "animesail.tv", "animesalt.net", "animesalt.to",
        "animesama.us", "animesaturn.com", "animesaturn.cx", "animesaturn.in",
        "animeschedule.net", "animescx.com.br", "animeseries.so", "animesfoxbr.com",
        "animesheaven.com", "animesheaven.net", "animesheep.com", "animeshot.ru",
        "animeshouse.app", "animesigma.com", "animesimp4u.com", "animesite2.blogspot.com",
        "animesnacional.com", "animesonglyrics.com", "animesongs.org", "animesonlinehd.info",
        "animesorionvip.com", "animesoul.com", "animesps.com", "animesrbija.com",
        "animesrgb.com", "animestars.org", "animestc.net", "animestone.com",
        "animestreamio.net", "animestreams.net", "animestreams.tv", "animesub.info",
        "animesuge.ai", "animesuge.cc", "animesuge.com", "animesuge.com.lv",
        "animesuge.io", "animesuge.link", "animesuge.me", "animesuge.pro",
        "animesuge.ru", "animesuge.se", "animesuge.skin", "animesuge.to",
        "animesuge.tv", "animesugeto.com", "animesugetv.to", "animesugez.to",
        "animesuki.com", "animesup.net", "animeszone.net", "animet.site",
        "animetake.su", "animetake.tv", "animethemes.moe", "animethere.com",
        "animetime.pw", "animetorrents.me", "animetorrents.ro", "animetosho.org",
        "animetribes.ru", "animetsu.cc", "animetudes.com", "animetv-jp.net",
        "animetv.cc", "animetv.to", "animetwist.moe", "animetown.net",
        "animeua.club", "animeui.com", "animeuknews.net", "animeultima.su",
        "animeultima.to", "animeunited.com.br", "animeunity.to", "animeuwutv.com",
        "animevania.com", "animeverse.cc", "animevf.com", "animevice.com",
        "animevsub.eu.org", "animewatchparties.com", "animeworld.cx", "animeworld.so",
        "animewriter.files.wordpress.com", "animewriter.wordpress.com", "animexico.forumup.com.mx", "animexin.info",
        "animexin.xyz", "animixplay.im", "animixplay.to", "animeyy.net",
        "animez.net", "animez.pro", "animeskai.com", "anitaku.pe",
        "anitaku.to", "anitown.net", "anitown.to", "aniwave.com.se",
        "aniwave.to", "aniwatch.to", "aniwatchtv.to", "anix.to",
        "anix.vip", "anizone.net", "anoboy.media", "anoboy.online",
        "api.instagram.com", "asmhentai.com", "asmhentai.to", "asuracomic.net",
        "asurascans.com", "baidu.com", "bakashi.tv", "bato.to",
        "bilibili.tv", "bing.com", "brave.com", "chia-anime.su",
        "cinezone.to", "comic-walker.com", "comick.io", "comixology.com",
        "crunchyroll.com", "dlsite.com", "donghuastream.co", "doujindesu.to",
        "doujindesu.tv", "doujins.com", "doujins.moe", "doujins.to",
        "dubbedanime.net", "duckduckgo.com", "e-hentai.org", "ea-hentai.com",
        "eahentai.com", "eahentai.to", "exhentai.org", "eyeonanime.tv",
        "fakku.net", "fbox.to", "fboxz.to", "freecomiconline.me",
        "freecomiconline.to", "gibiru.com", "global.bookwalker.jp", "global.toomics.com",
        "gogoanime.anl", "gogoanime.com", "gogoanime.fi", "gogoanime.tv",
        "gogoanimes.fi", "gogoanimes.so", "gojo.to", "gojo.wtf",
        "gojolive.io", "google.ch", "gomunime.is", "graph.instagram.com",
        "hbrowse.com", "hentai-envy.com", "hentai-era.com", "hentai-hand.com",
        "hentai-here.xxx", "hentai-manga.io", "hentai-manga.to", "hentai-read.com",
        "hentai-read.to", "hentai-rox.com", "hentai-rox.to", "hentai-zap.com",
        "hentai18.cc", "hentai18.net", "hentai18.org", "hentai18.to",
        "hentai20.com", "hentai20.io", "hentai20.to", "hentai20.to",
        "hentai20.io", "hentai2read.com", "hentai2read.to", "hentai2w.com",
        "hentaicafe.net", "hentaicafe.to", "hentaiclap.com", "hentaiclap.to",
        "hentaiclub.com", "hentaidb.com", "hentaidude.com", "hentaienvy.com",
        "hentaienvy.to", "hentaifox.com", "hentaifox.net", "hentaifox.to",
        "hentaifreak.org", "hentaihand.com", "hentaihand.to", "hentaihaven.to",
        "hentaihaven.xxx", "hentaihere.com", "hentaihere.to", "hentaihere.xxx",
        "hentailover.net", "hentaimama.com", "hentainet.com", "hentainexus.com",
        "hentainexus.to", "hentaiocean.com", "hentaipark.net", "hentaipornonly.com",
        "hentaira.com", "hentairaw.com", "hentairaw.net", "hentairead.com",
        "hentairead.to", "hentairox.com", "hentairox.to", "hentairun.com",
        "hentairun.to", "hentaispark.com", "hentaistream.com", "hentaiwebtoon.com",
        "hentaiwebtoon.to", "hentaiworld.eu", "hentaiworld.tv", "hentaivn.net",
        "hentaivn.to", "hentaizap.com", "hentaizap.to", "hentalk.com",
        "hentalk.to", "hentok.net", "hianime.bz", "hianime.cv",
        "hianime.do", "hianime.com", "hianime.nz", "hianime.org.vc",
        "hianime.pe", "hianime.sx", "hianime.to", "hianime.tv",
        "hianimez.to", "hikari.moe", "hitomi.la", "hitomi.to",
        "honeytoon.com", "honeytoon.to", "horriblesubs.info", "hotcomics.me",
        "i.instagram.com", "imhentai.com", "imhentai.to", "imhentai.xxx",
        "inkr.com", "instagram.com", "irodoricomics.com", "justdubs.org",
        "kakaopage.com", "kayoanime.com", "kickassanime.am", "kickassanime.rs",
        "kimcartoon.li", "kiryuu.id", "kiryuu.to", "kissanime.cfd",
        "kissanime.com", "kissanime.com.ru", "kissanime.ru", "kisskh.me",
        "kodansha.us", "komiku.id", "komiku.to", "kunmanga.com",
        "kunmanga.to", "kuudereto.net", "l.instagram.com", "lezhinus.com",
        "libbyapp.com", "likemanga.in", "lmanime.com", "luciferdonghua.in",
        "m-hentai.com", "m-hentai.net", "m-hentai.to", "m.instagram.com",
        "manga-buddy.com", "manga-r18.com", "mangadex.org", "mangafire.to",
        "mangafreak.com", "mangago.me", "mangahasu.me", "mangahere.cc",
        "mangakakalot.com", "mangakakalot.to", "mangaku.pro", "manganelo.com",
        "mangaowl.io", "mangapark.io", "mangapark.net", "mangapark.to",
        "mangaplanet.com", "mangaplus.shueisha.co.jp", "mangareader.to", "mangastream.net",
        "mangazin.org", "mangazoneapp.com", "mangahentai.io", "mangahentai.me",
        "mangahentai.to", "manhwa-raw.com", "manhwa18.cc", "manhwa18.net",
        "manhwa18.org", "manhwa18.to", "manhwa68.com", "manhwa68.to",
        "manhwaclan.com", "manhwaclan.net", "manhwaclan.to", "manhwafull.com",
        "manhwahentai.me", "manhwahentai.net", "manhwahentai.to", "manhwaland.com",
        "manhwaread.com", "manhwaread.to", "manhwas.net", "manhwax.com",
        "manhwax.to", "manta.net", "manytoon.com", "manytoon.to",
        "masterani.me", "masteranime.es", "metasearx.com", "miruro.tv",
        "moekyun.co", "multporn.com", "multporn.net", "multporn.to",
        "myanime.live", "myanimeindo.net", "mygogoanime.cyou", "nanime.tv",
        "naruldonghua.in", "neonime.nu", "nhentai.com", "nhentai.net",
        "nhentai.to", "nhentai.xxx", "niadd.com", "ninimanga.com",
        "nyaa.land", "nyaa.si", "onlythebest-hentai.com", "onlythebesthentai.com",
        "onlythebesthentai.to", "oploverz.bz", "otakudesu.org", "otakustream.tv",
        "pornhwaz.com", "pornhwaz.to", "presearch.com", "pururin.io",
        "pururin.to", "qwant.com", "rawkiss.com", "retrocru.sh",
        "riie.jp", "rine.cloud", "ryuanime.com", "s2manga.com",
        "samehadaku.tv", "search.brave.com", "simply-hentai.com", "streamversea.qzz.io",
        "taadd.com", "tapas.io", "tappytoon.com", "toongod.com",
        "toonily.com", "toonily.to", "topchineseanime.org", "torlock.com",
        "tsumino.com", "tubitv.com", "twist.moe", "uncensoredhentai.org",
        "uniquestream.net", "vidcloud.io", "viz.com", "vymanga.net",
        "watchcartoononline.com", "wcostream.tv", "webcomicsapp.com", "webtoon.xyz",
        "webtoons.com", "weebcentral.com", "www.instagram.com", "www.nhentai.net",
        "www1.ryuanime.com", "www2.animetv.to", "yandex.com", "zinmanga.net",
        "zinmanga.to", "zoro.to", "zoroxtv.to"
    ];

    for (var j = 0; j < denyList.length; j++) {
        if (dnsDomainIs(host, denyList[j]) || localHostOrDomainIs(host, denyList[j])) {
            // Change proxy settings below according to your setup:
            // "PROXY 127.0.0.1:8080" (Route through local proxy)
            // "PROXY 0.0.0.0:80" (Drop/Block traffic)
            return "PROXY 127.0.0.1:8080";
        }
    }

    // =========================================================================
    // 3. DEFAULT BEHAVIOR
    // =========================================================================
    return "DIRECT";
}
